apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: h3v52bmg8-nodejs-gitops
  description: This is GitOps manifest for h3v52bmg8-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: h3v52bmg8-nodejs
    janus-idp.io/tekton: h3v52bmg8-nodejs
    backstage.io/kubernetes-id: h3v52bmg8-nodejs 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:h3v52bmg8-nodejs
